// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnterCompactMode() {
  return window['go']['main']['App']['EnterCompactMode']();
}

export function ExitCompactMode() {
  return window['go']['main']['App']['ExitCompactMode']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}
