// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnterCompactMode():Promise<void>;

export function ExitCompactMode():Promise<void>;

export function Quit():Promise<void>;

export function Scan():Promise<main.ScanResult>;
